apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-info
  labels:
    app: hotel-info
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: hotel-info
  template:
    metadata:
      labels:
        app: hotel-info
    spec:
      containers:
        - name: hotel-info
          image: ip13/hotel-info
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          ports:
            - containerPort: 8501