apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade
  labels:
    app: grade
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: grade
  template:
    metadata:
      labels:
        app: grade
    spec:
      containers:
        - name: grade
          image: ip13/grade
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          ports:
            - containerPort: 8505