apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ip13/auth
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          ports:
            - containerPort: 8500