spring.application.name: hotel-booking

info.app.name: ${spring.application.name}

server.port: 8502

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-booking-info:5432/db
    username: postgres
    password: postgres

eureka.client.enabled: false

springdoc:
  api-docs:
    path: /auth/v3/api-docs
  swagger-ui:
    path: /auth/swagger-ui.html
