spring.application.name: grade

info.app.name: ${spring.application.name}

server.port: 8505

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-grade:5432/db
    username: postgres
    password: postgres

eureka.client.enabled: false

kafka:
  consumer:
    restaurant-created-event-consumer:
      bootstrap-servers: restaurant-created-event-kafka-bootstrap:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: restaurant-created
      properties.spring.json.type.mapping: restaurant-created-event:com.ip13.main.event.RestaurantCreatedEvent